
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seif
 */
public class manageemp extends javax.swing.JFrame {

    /**
     * Creates new form manageemp
     */
    public manageemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        win_exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        edit_emp = new com.k33ptoo.components.KButton();
        username_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_emp = new com.k33ptoo.components.KButton();
        username_field2 = new javax.swing.JTextField();
        username_field3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username_field4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        username_field5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        delete_emp = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new Color(0,0,0,0));
        kGradientPanel1.setkEndColor(new java.awt.Color(52, 152, 219));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(46, 204, 113));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        win_exit.setBackground(new java.awt.Color(0, 153, 204));
        win_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        win_exit.setForeground(new java.awt.Color(255, 255, 255));
        win_exit.setText("X");
        win_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                win_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(win_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, -10, 30, 90));

        jScrollPane1.setViewportView(jList1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 350, 340));

        edit_emp.setText("Edit");
        edit_emp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        edit_emp.setkBorderRadius(40);
        edit_emp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        edit_emp.setkPressedColor(new java.awt.Color(52, 152, 219));
        edit_emp.setOpaque(false);
        edit_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_empActionPerformed(evt);
            }
        });
        kGradientPanel1.add(edit_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 130, 40));

        username_field.setBackground(new Color(0,0,0,0));
        username_field.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username_field.setForeground(new java.awt.Color(255, 255, 255));
        username_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_field.setCaretColor(new java.awt.Color(52, 152, 219));
        username_field.setOpaque(false);
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 290, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Position");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 140, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Empolee");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 110, 30));

        add_emp.setText("Add");
        add_emp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add_emp.setkBorderRadius(40);
        add_emp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        add_emp.setkPressedColor(new java.awt.Color(52, 152, 219));
        add_emp.setOpaque(false);
        add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_empActionPerformed(evt);
            }
        });
        kGradientPanel1.add(add_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 130, 40));

        username_field2.setBackground(new Color(0,0,0,0));
        username_field2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username_field2.setForeground(new java.awt.Color(255, 255, 255));
        username_field2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_field2.setCaretColor(new java.awt.Color(52, 152, 219));
        username_field2.setOpaque(false);
        username_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 290, 40));

        username_field3.setBackground(new Color(0,0,0,0));
        username_field3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username_field3.setForeground(new java.awt.Color(255, 255, 255));
        username_field3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_field3.setCaretColor(new java.awt.Color(52, 152, 219));
        username_field3.setOpaque(false);
        username_field3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 180, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Empolee");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 140, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit Empolee:");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 140, 30));

        username_field4.setBackground(new Color(0,0,0,0));
        username_field4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username_field4.setForeground(new java.awt.Color(255, 255, 255));
        username_field4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_field4.setCaretColor(new java.awt.Color(52, 152, 219));
        username_field4.setOpaque(false);
        username_field4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username_field4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 180, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("name");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 140, 30));

        username_field5.setBackground(new Color(0,0,0,0));
        username_field5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        username_field5.setForeground(new java.awt.Color(255, 255, 255));
        username_field5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_field5.setCaretColor(new java.awt.Color(52, 152, 219));
        username_field5.setOpaque(false);
        username_field5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username_field5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 180, 40));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 140, 30));

        delete_emp.setText("Delete");
        delete_emp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete_emp.setkBorderRadius(40);
        delete_emp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        delete_emp.setkPressedColor(new java.awt.Color(52, 152, 219));
        delete_emp.setOpaque(false);
        delete_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_empActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delete_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void win_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_win_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_win_exitMouseClicked

    private void edit_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_empActionPerformed

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldActionPerformed

    private void add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_empActionPerformed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void username_field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field2ActionPerformed

    private void username_field3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field3ActionPerformed

    private void username_field4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field4ActionPerformed

    private void username_field5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field5ActionPerformed

    private void delete_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_empActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton add_emp;
    private com.k33ptoo.components.KButton delete_emp;
    private com.k33ptoo.components.KButton edit_emp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField username_field;
    private javax.swing.JTextField username_field2;
    private javax.swing.JTextField username_field3;
    private javax.swing.JTextField username_field4;
    private javax.swing.JTextField username_field5;
    private javax.swing.JLabel win_exit;
    // End of variables declaration//GEN-END:variables
}
