
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seif
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        win_exit = new javax.swing.JLabel();
        drinks = new com.k33ptoo.components.KButton();
        desserts = new com.k33ptoo.components.KButton();
        pizza = new com.k33ptoo.components.KButton();
        order_recipt_button = new com.k33ptoo.components.KButton();
        maindishes = new com.k33ptoo.components.KButton();
        menu_recipt = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        all_menu = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        menu = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new Color(0,0,0,0));
        kGradientPanel1.setkEndColor(new java.awt.Color(52, 152, 219));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(46, 204, 113));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        win_exit.setBackground(new java.awt.Color(0, 153, 204));
        win_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        win_exit.setForeground(new java.awt.Color(255, 255, 255));
        win_exit.setText("X");
        win_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                win_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(win_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, -10, 30, 90));

        drinks.setText("Drinks");
        drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksActionPerformed(evt);
            }
        });
        kGradientPanel1.add(drinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 120, 40));

        desserts.setText("Desserts");
        kGradientPanel1.add(desserts, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 120, 40));

        pizza.setText("Pizza");
        kGradientPanel1.add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 120, 40));

        order_recipt_button.setText("Order");
        order_recipt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_recipt_buttonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(order_recipt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 120, 40));

        maindishes.setText("Main Dishs");
        kGradientPanel1.add(maindishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 120, 40));
        kGradientPanel1.add(menu_recipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 220, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please choose what you want for tonight:");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 360, 30));

        all_menu.setText("All");
        kGradientPanel1.add(all_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 120, 40));

        jScrollPane2.setViewportView(menu);

        kGradientPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 400, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void win_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_win_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_win_exitMouseClicked

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinksActionPerformed

    private void order_recipt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_recipt_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_recipt_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton all_menu;
    private com.k33ptoo.components.KButton desserts;
    private com.k33ptoo.components.KButton drinks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private java.awt.List list1;
    private com.k33ptoo.components.KButton maindishes;
    private javax.swing.JList<String> menu;
    private java.awt.List menu_recipt;
    private com.k33ptoo.components.KButton order_recipt_button;
    private com.k33ptoo.components.KButton pizza;
    private javax.swing.JLabel win_exit;
    // End of variables declaration//GEN-END:variables
}
